server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/employee/**
        - id: employeeModule2
          uri: http://localhost:8081/
          predicates:
            - Path=/users/*/employee/**
          filters:
            - RewritePath=/users/*/(?<segment>.*), /$\{segment}
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**